title: afanasev.net
description: Boring coding
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://afanasev.net" # the base hostname & protocol for your site, e.g. http://example.com
author: Anatolii Afanasev
linkedin_username: aafanasev 
github_username: aafanasev

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-tidy
  - jekyll-sitemap

google_analytics: UA-60387111-7
disqus:
  shortname: afanasev-net