title: afanasev.net
email: tafanasyev@gmail.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://afanasev.net" # the base hostname & protocol for your site, e.g. http://example.com
author: Anatolii Afanasev
linkedin_username: aafanasev 
github_username: aafanasev

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-minifier

jekyll-minifier:
  compress_css: true 

google_analytics: UA-60387111-7
disqus:
  shortname: afanasev-net