name: Deploy Jekyll

on:
  push: 
    branches:
      - master
    paths:
      - '_jekyll/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Run jekyll build
        run: |
          cd _jekyll
          gem install bundler
          bundle install
          bundle exec jekyll build
      - name: Move build output to root dir
        run: mv ./_jekyll/_site/* ../
      - uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          title: Jekyll
          labels: auto-deploy, jekyll
          branch: jekyll
          branch-suffix: timestamp
